### PR TITLE
Add type to asset objects

### PR DESCRIPTION
**Pull request by hhunaid**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

Mime types were marked as TODO. This PR adds support for them. 

## Test Plan (required)

Select media and observe the `assets` array - it should have the correct mime type in the `type` key.

### CODE REVIEW

**Comment by kamranpirwani** [comment]
@hhunaid Thanks for adding, exactly what was needed on our side

**Comment by Johan-dutoit** [comment]
This looks good, although missing documentation.

**Review by dylanpyle — APPROVED** [review]
Functionality-wise, confirmed that this solves #1823 👌

**Review by Johan-dutoit — APPROVED** [review]

**Comment by afilp** [comment]
Can I restrict he picking to only mp4?

**Pull request merged**
