### PR TITLE
fix: wrong types path (#1554)

### PR DESCRIPTION
**Pull request by xgenem**
Fix for Cannot find module 'react-native-image-picker' or its corresponding type declarations. #1554

## Motivation (required)

What existing problem does the pull request solve?

This fixes the issue 'Cannot find module 'react-native-image-picker' or its corresponding type declarations.' #1554 

## Test Plan (required)

Tested fine after changing `types` path.

### CODE REVIEW

**Comment by xgenem** [comment]
I have a feeling that it is eslint's default configuration that showed this warning. But here's my tsconfig file and .eslintrc.json 

```tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "strict": true
  },
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
  "exclude": [
    "node_modules",
    "babel.config.js",
    "jest.config.js",
    "**/*.test.ts",
    "**/*.test.tsx"
  ]
}
```

```.eslintrc.json
{
  "extends": [
    "@react-native-community",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript"
  ],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "import"],
  "overrides": [
    {
      "files": ["__mocks__/**/*.ts", "__mocks__/**/*.tsx"],
      "env": {
        "jest": true
      }
    }
  ],
  "settings": {
    "import/ignore": ["node_modules/react-native/index\\.js$"],
    "import/extensions": [".js", ".jsx", ".ts", ".tsx"],
    "import/order": [
      "error",
      {
        "groups": ["builtin", "external", "internal"],
        "pathGroups": [
          {
            "pattern": "react",
            "group": "external",
            "position": "before"
          },
          {
            "pattern": "@moxie/**",
            "group": "internal",
            "position": "after"
          }
        ],
        "pathGroupsExcludedImportTypes": ["react"],
        "newlines-between": "always",
        "alphabetize": {
          "order": "asc",
          "caseInsensitive": true
        }
      }
    ]
  },
  "rules": {
    "react-native/no-unused-styles": "error",
    "react-native/sort-styles": ["error", "asc"],
    "react-hooks/exhaustive-deps": "warn",
    "import/no-unresolved": "off",
    "import/namespace": "off",
    "react/jsx-sort-props": [
      "error",
      {
        "ignoreCase": true
      }
    ],
    "@typescript-eslint/no-unused-vars": "off"
  }
}

```

Curious if it matters, there's no `src` directory inside `lib/typescript`. Shouldn't it be an obvious fix?

**Comment by Johan-dutoit** [comment]
@xgenem good point about there being no `src` directory inside the `lib/typescript` folder.  

Having a look at the history, it was [changed away](https://github.com/react-native-image-picker/react-native-image-picker/pull/1515/files) from this PR to include `src`.

Let me investigate a bit more.

**Comment by Johan-dutoit** [comment]
When I build the package locally, it does have `lib/typescript/src/index.ts`:
image

When viewing the package via my node_modules (where I install via npm), it doesn't include the src folder:
image

Nor is it included on unpkg: https://unpkg.com/browse/react-native-image-picker@3.1.3/lib/typescript/

**Comment by Johan-dutoit** [comment]
The folder still existed in 3.1.1.  The only real change I can think of then was CI deployments, as no relevant code changed.

**Review by Johan-dutoit — APPROVED** [review]
LGTM

**Comment by xgenem** [comment]
Thanks! I find it weird. Thanks for staying on top of this.

**Pull request merged**
