### PR TITLE
feat(ios): return fileSize of video on iOS

### PR DESCRIPTION
**Pull request by helenaford**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `main` branch, NOT a "stable" branch.

## Motivation (required)

Helps when validating a video a user has selected and helps to know if you need to optimize the video based on its file size

### CODE REVIEW

**Comment by andrey-shostik** [comment]
@Johan-dutoit Please merge the improvement

**Comment by Johan-dutoit** [comment]
My concern with merging this

- Docs says photos only
- Android video size missing

I'm happy with android being skipped (for now) in favour of the docs saying video only for ios

**Comment by helenaford** [comment]
@Johan-dutoit thanks for the feedback, I've updated the docs to reflect the changes to the API 🙏

**Review by Johan-dutoit — APPROVED** [review]

**Pull request merged**
