### PR TITLE
Fix: image orientation issue on android

### PR DESCRIPTION
**Pull request by ravirajn22**
Fixes 
https://github.com/react-native-image-picker/react-native-image-picker/issues/1466
https://github.com/react-native-image-picker/react-native-image-picker/issues/1338
And should fix orientation related issues on android

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
@jladuval please test these changes.

**Comment by jladuval** [comment]
This works great @Johan-dutoit! Thanks

**Comment by ravirajn22** [comment]
@Johan-dutoit we can merge it

**Comment by ravirajn22** [comment]
Going forward every PR merge requires a release. If possible can you automate it @Johan-dutoit .

**Comment by krakz999** [comment]
I'm on `3.0.1`, photos taken with `launchCamera` are still rotated by 90° when I post it to the backend. (other images are not)

**Comment by ravirajn22** [comment]
First check if it's in proper orientation when used with Image component.

**Comment by krakz999** [comment]
> First check if it's in proper orientation when used with Image component.

It is. Both gallery and photo images have the correct orientation in <Image/>. But only photos are rotated by 90° when uploaded.

**Comment by ravirajn22** [comment]
So the problem is in your backend, it should consider the image orientation exif data from the image for processing

**Comment by krakz999** [comment]
> So the problem is in your backend, it should consider the image orientation exif data from the image for processing. Google it.

Turns out `sharp` does not take the orientation tag into consideration without calling `rotate()` on it.
https://sharp.pixelplumbing.com/api-operation#rotate

Thanks for getting back!

**Pull request merged**
