### PR TITLE
docs(readme): updated iOS Response object fileName property

### PR DESCRIPTION
**Pull request by yerevin**
## Motivation

I ran into issue with fileName being undefined on iOS on videos when tried to parse it
fileName property is available only for Android photos/videos and photos in iOS, on iOS video fileName is undefined.

## Test Plan

This is only README update so I don't think any test plan is needed

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
Is there not a code change needed instead, to support it for iOS videos?

**Comment by yerevin** [comment]
Code change can be better solution for this, but I don't know Objective-C, so decided to at least "help" in this way :)

**Comment by Johan-dutoit** [comment]
Fair enough! If you can raise an issue as well please, then ideally someone that is familiar with Objective-C can take a look.
This can then get merged in until a fix is applied.

**Comment by yerevin** [comment]
#1670

**Comment by ravirajn22** [comment]
Thanks for putting effort to open a PR. This will be fixed in library.

**Pull request closed without merging**
