### PR TITLE
[iOS] Add latitude, longitude and dateTime

### PR DESCRIPTION
**Pull request by GoygovRustam**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)
Big part of working with images is being able to identify the location where the photo was taken as well as the time when that photo was taken.

What existing problem does the pull request solve?
There is existing issue (even though it is closed) where people are not able to get location.
https://github.com/react-native-image-picker/react-native-image-picker/issues/178

## Test Plan (required)
I have tested this on my phone. There is no automates tests in the repo.

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9

### CODE REVIEW

**Comment by clemencov** [comment]
Looks like it crashes when a photo doesn't have date-time info.

**Comment by ansarikhurshid786** [comment]
any update ?

**Comment by GoygovRustam** [comment]
> any update ?
> 
> 

Did not have time to look into it yet, but please feel free to update this PR. It just needs a null check. Otherwise I might take a look later

**Comment by ansarikhurshid786** [comment]
I don't have knowledge for this. please update i am waiting for it.

**Comment by ansarikhurshid786** [comment]
@GoygovRustam did you get time? please and commit pr

**Comment by acontass** [comment]
Any update ? Please 🙏

**Comment by GoygovRustam** [comment]
Hi @clemencov,  could you please review this PR again? I have added a null check but I don't have a way to test this (don't have a setup I had when I created this PR). Also I'm 0% familiar with this language so I'm not sure if this is the right way to handle null check here. Thank you.

**Comment by acontass** [comment]
@Johan-dutoit @clemencov Can someone review this PR please ?

**Comment by lukebrandonfarrell** [comment]
Yeah I can review, a few things:

- **Do you need permissions to access these values?** <-- Important as will impact how I CR this
- Could we update the README?
- If you rebase your code there is no need to include `datetime` in this PR?

Thanks

**Comment by GoygovRustam** [comment]
I really needed this change at some point and made this commit hoping it would not require much input, but I don't really know Objective C and can't contribute further. I would encourage someone who has experience in this language to make these changes in an appropriate way. Thank you.

**Comment by lukebrandonfarrell** [comment]
Gotcha @GoygovRustam, going to close this PR as datetime is already supported, and someone can add long and lat in the future

**Comment by alexg-93** [comment]
any update on gps location ? not working on ios when taking the picture cant get the extra data exif

**Comment by lukebrandonfarrell** [comment]
Because the structure changed on how we extract metadata @alexg-93 we would need to make a separate PR for location metadata

**Pull request closed without merging**
