### PR TITLE
feat(web): adding initial support for web.

### PR DESCRIPTION
**Pull request by mateoguzmana**
- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `main` branch, NOT a "stable" branch.

## Motivation

I stumbled across the problem for the web support whilst implementing a personal project using this library. I saw https://github.com/react-native-image-picker/react-native-image-picker/issues/1430 and going through the comments saw https://github.com/react-native-image-picker/react-native-image-picker/issues/1430#issuecomment-778700098 referring that expo has an implementation for web for their `expo-image-picker` library.

So I took inspiration from it and decided to start working on an initial web support which for now will support only the `launchImageLibrary` with `photos`.

## Test Plan

I integrated `react-native-web` for the example project to be able to have an integrated example of the web support.

You can see it working below:

https://user-images.githubusercontent.com/20783123/183108425-e3a1cd47-7f19-42cd-95df-cca235222c26.mov

## In this PR

- Support for React Native Web using the same API. The existing methods remain working as they were for iOS and Android.
- Initial support only for launchImageLibrary with the option to pick `photos` only.
- Allows single and multiple selection.
- Supports base64.
- Docs updated including web specifications.
- Example project updated and using react-native-web.

## What's next?

If this gets approved I will volunteer myself to add the support for videos and mixed selection as well as trying to give web support for `launchCamera`. I already have some internal drafts for those but it needs more work.

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
Tremendous effort!   I'll attempt to test & review it soon.

**Comment by Johan-dutoit** [comment]
Apologies for the delay.  Tiny confict.

**Comment by mateoguzmana** [comment]
No worries @Johan-dutoit :)

Btw, the last changes seem to have a change in the [README](https://github.com/react-native-image-picker/react-native-image-picker/blob/main/README.md) that makes one of the tables non-readable so I'm fixing that in this PR as well.

Conflicts solved.

**Review by Johan-dutoit — APPROVED** [review]

**Pull request merged**
