### PR TITLE
Dispatch UIKit actions onto main thread

### PR DESCRIPTION
**Pull request by SmartArray**
## Motivation 

UIKit warnings about ImagePickerController not being called from main thread. This also slows down the launch of the ImagePicker.
Hence, wrapping all initialization functions into main-queue dispatch easily solves the issue.
Note that this won't have any implications on the main thread since all actions are considered as cheap. 

## Test Plan

This little change only needs to be tested on a physical device.
I've tested this on an iPhone SE (iOS 12) and an iPhone X (iOS 13.3) device. No issues at all.

### CODE REVIEW

**Comment by zabojad** [comment]
Could that be merged soon?

**Comment by fasterhousekeeping** [comment]
Any word on when this will be merged?
Thanks

**Comment by mcbeyel** [comment]
The patch needs additionally to be applied to `launchImagePicker`:

`- (void)launchImagePicker:(RNImagePickerTarget)target
{
    dispatch_async(dispatch_get_main_queue(), ^{`

**Comment by nshaposhnik** [comment]
For me, it fixes the issue (error in XCode logs plus slowdown before permissions dialog), but then after I press OK, there's another one and crash:
`2019-12-25 15:41:31.549652+0200 Bezala[1417:619112] [Animation] +[UIView setAnimationsEnabled:] being called from a background thread. Performing any operation from a background thread on UIView or a subclass is not supported and may result in unexpected and insidious behavior. trace=(
	0   UIKitCore                           0x00000001c59e1fa4 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 15241124
	1   libdispatch.dylib                   0x00000001034d2bd8 _dispatch_client_callout + 16
	2   libdispatch.dylib                   0x00000001034d44c8 _dispatch_once_callout + 84
	3   UIKitCore                           0x00000001c59e1f08 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 15240968
	4   UIKitCore                           0x00000001c59e2090 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 15241360
	5   UIKitCore                           0x00000001c53c7cd8 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 8842456
	6   UIKitCore                           0x00000001c5788a40 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 12778048
	7   UIKitCore                           0x00000001c55a5ff8 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 10801144
	8   UIKitCore                           0x00000001c4f3fd90 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4091280
	9   UIKitCore                           0x00000001c4f5f1a4 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4219300
	10  UIKitCore                           0x00000001c4f50244 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4158020
	11  UIKitCore                           0x00000001c4f51bd4 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4164564
	12  UIKitCore                           0x00000001c4f540b0 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4174000
	13  UIKitCore                           0x00000001c4f545ac B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4175276
	14  UIKitCore                           0x00000001c4f54000 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4173824
	15  UIKitCore                           0x00000001c4f54268 B7E79AF1-F09F-3BCE-B073-ECEA027BC0E8 + 4174440
	16  Bezala                              0x0000000102d1bfd8 __40-[ImagePickerManager launchImagePicker:]_block_invoke_2 + 88
	17  TCC                                 0x00000001c76d1b60 03E8D082-B885-3FA8-A1DA-CCB21D26FE1A + 7008
	18  TCC                                 0x00000001c76d5b28 03E8D082-B885-3FA8-A1DA-CCB21D26FE1A + 23336
	19  libxpc.dylib                        0x00000001c10cac84 219DEC3C-E62E-395D-8911-FB74F73A5598 + 97412
	20  libxpc.dylib                        0x00000001c10bef18 219DEC3C-E62E-395D-8911-FB74F73A5598 + 48920
	21  libdispatch.dylib                   0x00000001034d2c58 _dispatch_client_callout3 + 16
	22  libdispatch.dylib                   0x00000001034ee29c _dispatch_mach_msg_async_reply_invoke + 388
	23  libdispatch.dylib                   0x00000001034e503c _dispatch_kevent_worker_thread + 1376
	24  libsystem_pthread.dylib             0x00000001c120efc0 _pthread_wqthread + 332
	25  libsystem_pthread.dylib             0x00000001c1211ad4 start_wqthread + 8
)`

iPhone SE 13.2.3

**Comment by EricWiener** [comment]
This fixed the error for me.

**Comment by MacMeDan** [comment]
It would be great if this could be reviewed and merged.

**Comment by Johan-dutoit** [comment]
Mostly looks good, except the new error appearing.
Can anyone comment on that?

**Comment by kmh0237** [comment]
Please use https://github.com/react-native-community/react-native-image-picker/pull/1265  instead, ok button is completely broken when asking for permissions and the other guy's fix is better anyway

**Pull request closed without merging**
