### PR TITLE
Add new architecture support

### PR DESCRIPTION
**Pull request by j-piasecki**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `main` branch, NOT a "stable" branch.

## Motivation (required)

This PR starts of where https://github.com/react-native-image-picker/react-native-image-picker/pull/2023 left off. Main changes on top of it are:
- upgrading the example app to React Native 0.71
- using the new codegen config
- updating the `build.gradle` to implement correct RN dependency based on the version
- removing `reac` block and some workarounds from `build.gradle`

## Test Plan (required)

Similarly to the original PR, I've tested the updated example app.

You can test the new architecture:
- on Android, set the `newArchEnabled` property to true in `gradle.properties`
- on iOS, use the set the `RCT_NEW_ARCH_ENABLED` flag, i.e. `RCT_NEW_ARCH_ENABLED=1 pod install`

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
Thanks @j-piasecki, I imagine this requires a huge testing effort.
Unfortunately no one gave any feedback on #2023, which is why it stagnated.

**Comment by mountiny** [comment]
@Johan-dutoit Hello! Is there any list of testing steps that should be taken in the Example app which we could meet/verify to provide sufficient confidence this works or to discover potential issues? I think we could try to get some of our open-source contributors to help with the testing or we can also reward you for testing this if you have time for this and works better for you?

**Comment by mountiny** [comment]
@j-piasecki can also test this thoroughly if there is some list of steps/things to test.

**Comment by Johan-dutoit** [comment]
Hey, I did some preliminary testing and it's looking good so far.  I did need to bump some dev dependencies in the main repo to get the typescript to build, which I'll commit to this shortly.

What I'll do part of a separate PR is throw together a `TESTING.md` of sorts, for folk to use as a starting point for testing.

**Comment by satheshrgs** [comment]
@j-piasecki 

Is there any beta version for this ?

I am currently facing this issue - https://github.com/react-native-image-picker/react-native-image-picker/issues/2084

Just wondering that if it got fixed in the latest ?

**Comment by Johan-dutoit** [comment]
I've done what I feel is a good amount of testing.  
Various devices, platforms, new arch enabled/disabled, along with various file types.

My examples `podfile.lock` file is dirty, so will likely do another push to the branch before merging.  

Otherwise, looking good 🚀

**Review by Johan-dutoit — APPROVED** [review]

**Comment by mountiny** [comment]
Wohoo, thanks @Johan-dutoit ! 🎉

**Pull request merged**
