### PR TITLE
fix(gradle): 🐛 align gradle versions

### LINKED ISSUE #1696: use a compatible library with a minSdk of at most 16,
### Description

I have the following error using the latest version :

```
ve-image-picker/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.imagepicker" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processApptestingDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:react-native-image-picker] /home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/react-native-image-picker/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.imagepicker" to force usage (may lead to runtime failures)


```
Looking at [`gradle.properties`](https://github.com/react-native-image-picker/react-native-image-picker/blob/v3.6.0/android/gradle.properties), the min sdk version is 16.

Why is the version in `build.gradle` mismatching ?

### PR DESCRIPTION
**Pull request by Johan-dutoit**
Closes #1696

### CODE REVIEW

**Comment by ravirajn22** [comment]
No this project requires min 21. You cannot have something smaller than that in your main project. So the library users have to upgrade their main projects minSdkVersion to >=21. Then the issue is solve.

**Comment by ravirajn22** [comment]
@Johan-dutoit u can close it.

**Comment by Johan-dutoit** [comment]
@ravirajn22 this is upgrading everything, not downgrading. i.e. making everything 21.

**Comment by rpander93** [comment]
I think what @ravirajn22 means that is the minSdkVersion is now tied to the users' app (which could theoretically be lt 16). This isnt correct.

btw, the gradle.properties file doesnt appear to be used at all in this project.

**Pull request closed without merging**
