### PR TITLE
Added main entry point to package.json

### PR DESCRIPTION
**Pull request by nberehova**
For some reason jest needs main entry point to mock this module.

Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)
I just want to make this module mockable by jest again.
Looks like this is the reason of issue #1485 .

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
Not entirely convinced it's needed.  Have a look at this PR: https://github.com/react-native-image-picker/react-native-image-picker/pull/1487/files

**Comment by ravirajn22** [comment]
@nberehova closing it for now. Update here if you have any comments, I am happy to review it.

**Comment by mewhit** [comment]
You should add "main": "src/index.ts" in package.json
If you add it, people using the libraries with JavaScript has nothing to set up for testing.
With the current state, the libraries force people to change how your jest setup actually work.

**Comment by mewhit** [comment]
Easiest WORKARROUND!
In jest.config add
`
 "moduleNameMapper": {
      "react-native-image-picker": "<rootDir>/mocks/react-native-image-picker.js"
    }
`
and in mocks/react-native-image-picker.js
`
export default {
  launchCamera: jest.fn(),
  launchImageLibrary: jest.fn(),
};
`

**Comment by ravirajn22** [comment]
Also fixes #1530

**Comment by Johan-dutoit** [comment]
Closing as this already exists on main.

**Pull request closed without merging**
