### PR TITLE
Feature: add option formatToMp4 to convert .mov to .mp4 in iOS

### PR DESCRIPTION
**Pull request by rizkisunaryo**
## Motivation (required)

When iOS records a video, the format is `.mov`.
When we upload this `.mov`, we can't play it in Chrome browser and some Android devices.
That's why, this `.mov` needs to be converted to `.mp4`

## Test Plan (required)

Tried recording, picking video from gallery, and uploading video from iOS. No crash happened. And the video could be played in Chrome.

### CODE REVIEW

**Comment by rkdavidson** [comment]
FWIW, We manually patched our `react-native-image-picker` via `patch-package` to include this PR's changes, and have been using it in production for ~1-2 months now with no issues.

We use it to convert `mov` files to `mp4` before uploading, as part of our app's chat feature.
This way, iOS users can send videos to all Android users in a consistent way. Previously, Samsung devices couldn't play `mov` files.

**Comment by Johan-dutoit** [comment]
Can the images be removed, seems like 2 were added for no reason?

**Comment by DISKONEKTeD** [comment]
so is not being merged?

**Comment by patissier-boulanger** [comment]
not merged yet??

**Comment by nica0012** [comment]
Any news here?

**Pull request closed without merging**
