### PR TITLE
refactor: return fileuri instead of contenturi in android

### PR DESCRIPTION
**Pull request by ravirajn22**
This should fix issues which wanted file uri to work easily with other libraries.

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
@ravirajn22 conflicts ☝️

**Comment by ravirajn22** [comment]
I will rebase and push

**Comment by ravirajn22** [comment]
Rebased, check now.

**Review by Johan-dutoit — APPROVED** [review]

**Comment by ravirajn22** [comment]
What we do release a major version? I feel there should not be any compatibility issues using fileUri from contentUri in Android. So we can just warn users in release notes and just release a minor version.

**Comment by ravirajn22** [comment]
@Johan-dutoit ?

**Comment by Johan-dutoit** [comment]
https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.3.2

**Comment by ravirajn22** [comment]
@Johan-dutoit can you add a warning in release notes like

"FileUri should be compatible with ContentUri so should work without any issues, but please check ones in your Android devices after upgrading to make sure. Report any issues. Thanks"

**Pull request merged**
