### PR TITLE
Added ability to include exif data for iOS and Android

### PR DESCRIPTION
**Pull request by lukebrandonfarrell**
Thanks for submitting a PR! Please read these instructions carefully:

- [X] Explain the **motivation** for making this change.
- [X] Provide a **test plan** demonstrating that the code is solid.
- [X] Match the **code formatting** of the rest of the codebase.
- [X] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

This adds the architecture for iOS and Android to optionally offer the ability to include exif data with the selected photos. The requires iOS library permissions, hence `includeExif` defaults to `false`.

## Test Plan (required)

These changes will be released to several thousand users in our production application via our fork.

### CODE REVIEW

**Comment by lukebrandonfarrell** [comment]
Need to do more regression testing, but would like some initial feedback from reviewers.

**Comment by lukebrandonfarrell** [comment]
Added iOS 13 and below support for Exif data. (still needs permissions). @Johan-dutoit could I get some initial feedback on this? Writing a comprehensive test plan now for all the scenarios, which I will manually QA and attach videos.

**Comment by lukebrandonfarrell** [comment]
@Johan-dutoit because PHAsset.fetch needs permissions, the permission dialog will appear when that native code is executed, maybe it's better to default `includeExif` to `false` when permissions are NOT granted, and make a note on the README that `includeExif` requires permissions to be asked before you open the picker to work. Let me know your thoughts

**Comment by ansarikhurshid786** [comment]
I am waiting for this update.

**Comment by lukebrandonfarrell** [comment]
@ansarikhurshid786 Want to give this a peer review (CR) then maybe we can get it through faster? Waiting for mod to give feedback on code, then will upload the QA I did of scenarios.

**Comment by ansarikhurshid786** [comment]
@lukebrandonfarrell  how long it will take to available?

**Comment by lukebrandonfarrell** [comment]
@ansarikhurshid786 I'm waiting on a mod to give me initial feedback @Johan-dutoit ??

**Comment by lukebrandonfarrell** [comment]
Do you want me to upload QA scenarios first @Johan-dutoit ? I was thinking a first round of CR, incase there are any changes, then test plan / QA scenarios, that would make more sense to me

**Comment by ansarikhurshid786** [comment]
@Johan-dutoit can you please give feedback and done it as soon as possible. i am eagerly waiting for this update.

**Comment by ansarikhurshid786** [comment]
@lukebrandonfarrell do this pr only include exif with timestamp only? I am looking for latitude and longitude from exif data

**Comment by lukebrandonfarrell** [comment]
@ansarikhurshid786 This PR only adds timestamp, but it adds a structure to allow easy addition of any permission-required metadata, if you want location it will be pretty straightforward to add

**Comment by helenaford** [comment]
@lukebrandonfarrell I branched off your p/r to return the local asset id for videos and images on iOS. I'm not sure if the flag `includeExif` should be renamed or I should add an additional flag because to acquire the id it needs to have permissions.

**Comment by Johan-dutoit** [comment]
Let's go with `includeExtra` before merging this (along with the time change).  We can move forward with additional 'extras' once this is in.

**Comment by helenaford** [comment]
@lukebrandonfarrell sounds good. thanks a lot for your work on this. I'm also away this week for Web Summit so won't be active much either.

**Comment by lukebrandonfarrell** [comment]
@Johan-dutoit Can you re-review the requested changes?

**Comment by lukebrandonfarrell** [comment]
@Johan-dutoit Still need a final review on this if you have time? Since it was from your recommendation to add UTC it would be good to get a quick thumbs up or thumbs down on the approach I implemented. Thanks

**Review by Johan-dutoit — APPROVED** [review]

**Comment by helenaford** [comment]
hey @lukebrandonfarrell @Johan-dutoit , was just checking in on this. awesome to see that it was released 😎  what are the next steps on merging the second p/r (https://github.com/Qeepsake/react-native-image-picker/pull/1)?

**Comment by lukebrandonfarrell** [comment]
@helenaford Any chance we could open that PR against this repo, and then I'll review it, and merge, tbh looks good to me!

**Comment by helenaford** [comment]
@lukebrandonfarrell sure,  will look into this over the next few days 😎

**Pull request merged**
