### PR TITLE
fix: change minSdkVersion for RN 0.74.1

### PR DESCRIPTION
**Pull request by MrRefactor**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `main` branch, NOT a "stable" branch.

## Motivation (required)

React Native 0.74.1 added [the minimum SDK version bump to 23](https://reactnative.dev/blog/2024/04/22/release-0.74#android-minimum-sdk-bump-android-60). This PR tends to add the same, making sure the previous 21 is intact.

## Test Plan (required)

Run example app on android.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9

### CODE REVIEW

**Comment by MrRefactor** [comment]
Hey hey @brentvatne @Johan-dutoit could you please take a look at this pr?

**Comment by raduiamandi-pilot** [comment]
This is currently affecting my builds too. :(

**Comment by MrRefactor** [comment]
hey hey @Johan-dutoit could you merge it?

**Comment by murilo-alvesmelo** [comment]
@Johan-dutoit merge please

**Comment by MrRefactor** [comment]
Ping @brentvatne @Johan-dutoit

**Comment by BogdanRad** [comment]
@MrRefactor can you update `compileSdkVersion` and `targetSdkVersion` in 34 for this issue? thank you 
image

**Comment by MrRefactor** [comment]
> @MrRefactor can you update `compileSdkVersion` and `targetSdkVersion` in 34 for this issue? thank you image

Please create separate PR for this, as its not a part of rn 0.74 changes

**Comment by professorkolik** [comment]
Any ETA when this will be merged?

**Comment by MrRefactor** [comment]
Hey hey @brentvatne @Johan-dutoit could you please take a look at this pr?

**Review by Johan-dutoit — APPROVED** [review]

**Comment by MrRefactor** [comment]
hey @Johan-dutoit thanks for merging this, could you release new version?

**Comment by aderiushev** [comment]
such a poor support, for sure will use another one, if u can't maintain it, make a call or deprecate it

**Pull request merged**
