### PR TITLE
Support mixed media type for launchImageLibrary

### LINKED ISSUE #1527: [🌟] Bring back mixed media type in v3
### Description

Support mixed media type like in V2.

### Proposed Solution

Accept `mixed` as a `mediaType` in `launchCamera` and `launchImageLibrary` like in v2

### PR DESCRIPTION
**Pull request by ravirajn22**
Closes #1527 

People can use this PR and test.

Release a beta version. @Johan-dutoit

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
@ravirajn22 conflicts 👇

**Comment by nero2009** [comment]
This currently breaks on ios 14, you might need to add this method
import PhotoUI

`#import <PhotosUI/PhotosUI.h>`

then add the configuration for it

`+ (PHPickerConfiguration *)makeConfigurationFromOptions:(NSDictionary *)options API_AVAILABLE(ios(14))
{
    PHPickerConfiguration *configuration = [[PHPickerConfiguration alloc] init];
    configuration.preferredAssetRepresentationMode = PHPickerConfigurationAssetRepresentationModeCurrent;

    return configuration;
}
`
We dont need to specify a filter because it allows videos and pictures by default

**Comment by Johan-dutoit** [comment]
@nero2009 can you confirm which version of xcode you're running?

**Comment by nero2009** [comment]
> @nero2009 can you confirm which version of xcode you're running?

12.4

**Comment by ravirajn22** [comment]
@Johan-dutoit rebased, please test ones and merge.

**Review by Johan-dutoit — APPROVED** [review]

**Comment by Johan-dutoit** [comment]
> This currently breaks on ios 14, you might need to add this method
> import PhotoUI
> 
> `#import <PhotosUI/PhotosUI.h>`
> 
> then add the configuration for it
> 
> ```
> + (PHPickerConfiguration *)makeConfigurationFromOptions:(NSDictionary *)options API_AVAILABLE(ios(14))
> {
>     PHPickerConfiguration *configuration = [[PHPickerConfiguration alloc] init];
>     configuration.preferredAssetRepresentationMode = PHPickerConfigurationAssetRepresentationModeCurrent;
> 
>     return configuration;
> }
> ```
> 
> We dont need to specify a filter because it allows videos and pictures by default

I'm not experiencing this issue on 14.5 (and xcode 12.4).  The filter is also in place as we're not showing/supporting live photos.

**Pull request merged**
