### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ravirajn22**
The commit messages should give an idea for the changes in this PL.

### CODE REVIEW

**Comment by ravirajn22** [comment]
Any updates?

**Comment by Johan-dutoit** [comment]
Hi @ravirajn22, as you can imagine.  These are pretty big PR's to review.
I'll add some feedback soon.

**Comment by ravirajn22** [comment]
Any updates? I am confident enough to let users try this branch. Initially people who are ready to migrate can start using and others can request for features which they think are missing.

You have to check the build output in npm ones, I have checked it locally.

**Comment by Johan-dutoit** [comment]
I've merged it into vnext!
I'll be running all the changes locally and will revert back.

**Comment by ravirajn22** [comment]
@Johan-dutoit can you add me with write permission for `vnext` branch?

**Pull request merged**
